<!-- 这个界面要实现的是显示客户的基本信息，通过电话号码准确定位到人 -->
<!-- 使用场景为：客户进入门店，提出租车需求，店员通过其提供的电话号码查询信息， -->
<!-- 了解其基础信息（违章，事故，姓名）便于开展下一步业务 -->

<!-- 下一步优化：可以在数据库表中加入例如常用租金区间，最常租用的车型，品牌等用户偏好提示设置， -->
<!-- 并可提供一个给店员添加的注释，标明用户的性格，喜好等 -->

<script setup lang="ts">
import DataTable from '@/components/DataTable.vue'
import { ROUTE_CUSTOMER_INFO } from '@/utils/constants';
import { genderConverter, trueFalseConverter } from '@/utils/converter'
import * as common from '@/utils/common'
</script>

<script lang="ts">
import { defineComponent } from 'vue'
import { dateConverter } from '@/utils/converter'
import { checkChineseName, dateTime, idCard, notEmpty, positiveNumber, StringUtils } from '@/utils/validator';
import { getUUID } from '@/utils/uuid';

export default defineComponent({
	data() {
		return {
			columns: [
				{
					field: 'id',
					label: '客户 ID',
					type: 'uuid',
					isValid: true,
					/**
					 * 指示是否由系统自动填入
					 */
					autoGenerated: true,
					validator: (value) => {
						notEmpty('id', value)
					}
				},
				{
					field: 'name',
					label: '姓名',
					isValid: false,
					validator: (value) => {
						const col = common.getColumn('name');
						col.isValid = checkChineseName(value);
					}
				},
				{
					field: 'card',
					label: '身份证号',
					isValid: false,
					showOnSummary: false,
					validator: (value) => {
						idCard('card', value)
						if (common.getColumn('card').isValid) {
							common.setDataValue('birthday', `${value.substring(6, 10)}-${value.substring(10, 12)}-${value.substring(12, 14)}`)
							common.setDataValue('age', new Date().getFullYear() - parseInt(value.substring(6, 10)))
							common.setDataValue('gender', value.substring(16, 17) % 2 === 0 ? false : true)
						} else {
							common.setDataValue('birthday', '')
							common.setDataValue('age', '')
							common.setDataValue('gender', '')
						}
					}
				},
				{
					field: 'phone',
					label: '电话号码',
					isValid: false,
					type: 'tel',
					validator: (value) => {
						const col = common.getColumn('phone')
						col.isValid = StringUtils.isPhone(value)
					}
				},
				{
					field: 'birthday',
					label: '生日',
					isValid: false,
					autoGenerated: true,
					showOnSummary: false,
					converter: dateConverter,
					validator: (value) => {
					}
				},//生日这个或许做成后台记录，
				//当用户生日时执行折扣或者弹窗或突出显示可能会更好
				{
					field: 'address',
					label: '常驻地',
					isValid: false,
					validator: (value) => {
						notEmpty('address', value)
					}
				},
				{
					field: 'age',
					label: '年龄',
					isValid: false,
					autoGenerated: true,
					type: 'number',
					validator: (value) => {
					}
				},
				{
					field: 'gender',
					label: '性别',
					isValid: false,
					type: 'boolean',
					autoGenerated: true,
					converter: trueFalseConverter,
					validator: (value) => {
					}
				},
				//违章次数和事故次数或许使用突出显示会更好（背景，字号，字体颜色）
				{
					field: 'violate_count',
					label: '违章次数',
					isValid: true,
					type: 'number',
					validator: (value) => {
						positiveNumber('violate_count', value)
					},
					autoGenerated: true,
				},
				{
					field: 'accident_count',
					label: '事故次数',
					isValid: true,
					type: 'number',
					validator: (value) => {
						positiveNumber('accident_count', value)
					},
					autoGenerated: true,
				}
			],
			baseURL: `${ROUTE_CUSTOMER_INFO}`
		};
	},
	created() {
		common.beforeAdd.value = () => {
			common.setDataValue('id', getUUID())
			common.setDataValue('violate_count', 0)
			common.setDataValue('accident_count', 0)
		}
		common.afterAdd.value = () => {

		}
	}
});
</script>

<template>
	<DataTable :columns="columns" :base-u-r-l="baseURL" />
</template>