<script setup lang="ts">
import { ROUTE_VEHICLE_MAINTENANCE } from '@/utils/constants';
import DataTable from '@/components/DataTable.vue';
import * as common from '@/utils/common'
</script>

<script lang="ts">
import { defineComponent } from 'vue';
// @ts-ignore
import { notEmpty, positiveNumber } from '@/utils/validator';

export default defineComponent({
  data() {
    return {
      columns: [
        {
          field: 'vid',
          label: '车辆ID',
          type: 'uuid',// @ts-ignore
          validator: (value) => {
            const col = common.getColumn('vid')
            col.isValid = (value !== "") // value === ''
          },
          isValid: false,
          autoGenerated: true,
        },
        {
          field: 'total_distance',
          label: '总里程',
          type: 'number',// @ts-ignore
          validator: (value) => { },
          isValid: false,
          autoGenerated: true,
        },
        {
          field: 'maintenance_fee',
          label: '保养费用',// @ts-ignore
          validator: (value) => {
            positiveNumber('maintenance_fee', value)
          },
          isValid: false,
          autoGenerated: true,
        },
        {
          field: 'maintenance_times',
          label: '保养次数',
          type: 'number',// @ts-ignore
          validator: (value) => {
            positiveNumber('maintenance_times', value, -1)
          },
          isValid: false
        }
      ],
      baseURL: `${ROUTE_VEHICLE_MAINTENANCE}`,
      setRowClass: (item: {}) => {// @ts-ignore
        if (Math.floor(item['total_distance'] / 10000) > item['maintenance_times']) {
          return 'table-danger'
        } else {
          return ''
        }
      }
    };
  },
  created() {// @ts-ignore
    common.beforeAdd.value = () => {

    }// @ts-ignore
    common.afterAdd.value = () => {

    }
  }
});
</script>

<template>
  <DataTable :columns="columns" :base-u-r-l="baseURL" :set-row-class="setRowClass" :allow-add="false"
    :allow-delete="false" />
</template>


