<script setup lang="ts">
import CardView from '@/components/CardView.vue'
import { ROUTE_VEHICLE_INFO, ROUTE_VEHICLE_MAINTENANCE } from '@/utils/constants'

</script>

<script lang="ts">
import { defineComponent } from 'vue'
import { trueFalseConverter } from '@/utils/converter'
import * as common from '@/utils/common'
import { dateTime, licensePlateCheck, notEmpty } from '@/utils/validator'
import http from '@/utils/http'
import { getUUID } from '@/utils/uuid'
import DataService from '@/services/data-service'

export default defineComponent({
  data() {
    return {
      columns: [
        {
          field: 'id',
          label: '车辆 ID',
          type: 'uuid',
          showOnSummary: true,
          autoGenerated: true,
          isValid: true,
          validator: (value) => {
          },
        },
        {
          field: 'manufacturer',
          label: '厂商',
          validator: (value) => {
            notEmpty('manufacturer', value)
          },
          isValid: false
        },
        {
          field: 'brand',
          label: '品牌',
          validator: (value) => {
            notEmpty('brand', value)
          },
          isValid: false
        },
        {
          field: 'color',
          label: '颜色',
          validator: (value) => {
            notEmpty('color', value)
          },
          isValid: false
        },
        {
          field: 'seat_count',
          label: '车座数',
          type: 'number',
          validator: (value) => {
            const col = common.getColumn('seat_count')
            col.isValid = (value !== "") && (parseInt(value) === 7 || parseInt(value) === 5|| parseInt(value) ===2)
          },
          isValid: false
        },
        {
          field: 'rental_fee',
          label: '日租金',
          type: 'number',
          validator: (value) => {
            const col = common.getColumn('rental_fee')
            col.isValid = (value !== "") && parseInt(value) > 0
              // && parseInt(value) < 10001
          },
          isValid: false
        },

        {
          field: 'energy_type',
          label: '是否新能源',
          type: 'boolean',
          converter: trueFalseConverter,
          validator: (value) => {
          },
          isValid: true
        },
        {
          field: 'accident',
          label: '是否发生事故',
          type: 'boolean',
          converter: trueFalseConverter,
          validator: (value) => {
          },
          isValid: true,
          autoGenerated: true
        },
        {
          field: 'lease_status',
          label: '是否已租借',
          type: 'boolean',
          showOnSummary: false,
          converter: trueFalseConverter,
          validator: (value) => {
          },
          isValid: true
        },

        {
          field: 'buy_time',
          label: '购买时间',
          type: 'date',
          showOnSummary: false,
          validator: (value) => {
            dateTime('buy_time', value)
          },
          isValid: false
        },
        {
          field: 'buy_price',
          label: '入库价格',
          type: 'number',
          showOnSummary: false,
          validator: (value) => {
            const col = common.getColumn('buy_price')
            col.isValid = (value !== "") && parseInt(value) >= 0
          },
          isValid: false
        },
        {
          field: 'license_plate_number',
          label: '车牌号码',
          showOnSummary: false,
          validator: (value) => {
            licensePlateCheck('license_plate_number', value)
          },
          isValid: false
        },
        {
          field: 'total_distance',
          label: '总里程数', type: 'number',
          showOnSummary: false,
          validator: (value) => {
            const col = common.getColumn('total_distance')
            col.isValid = (value !== "") && parseInt(value) >= 0
          },
          isValid: true,
          autoGenerated: true
        },
        {
          field: 'car_id',
          label: '车架号',
          showOnSummary: false,
          validator: (value) => {
            const col = common.getColumn('car_id')
            col.isValid = (value !== "") && value.length < 30
          },
          isValid: false
        },
        {
          field: 'img',
          label: '车辆图片',
          showOnSummary: false,
          validator: (value) => {
            const col = common.getColumn('img')
            col.isValid = (value !== "") // value === ''
          },
          isValid: false
        },
        //里程数需要联查
      ],
      baseURL: `${ROUTE_VEHICLE_INFO}`
    };
  },
  methods: {
  },
  created() {
    common.beforeAdd.value = () => {
      common.setDataValue('id', getUUID())
      common.setDataValue('energy_type', false)
      common.setDataValue('accident', false)
      common.setDataValue('lease_status', false)
      common.setDataValue('total_distance', 0)
    }
    common.afterAdd.value = async () => {
      let ds = new DataService(`${ROUTE_VEHICLE_MAINTENANCE}`)
      await ds.addAsync({
        vid: common.data.value['id'],
        total_distance: common.data.value['total_distance'],
        maintenance_status: '无需处理',
        maintenance_times: 0,
        maintenance_fee: parseInt(common.data.value['buy_price']) * 0.005,
      })
    }
  }
});
</script>

<template>
  <CardView :columns="columns" :base-u-r-l="baseURL" />
</template>

