<script setup lang="ts">
import {
  MDBModal, MDBModalHeader, MDBModalBody, MDBModalTitle, MDBModalFooter,
  MDBInput, MDBBtn, MDBRadio
} from 'mdb-vue-ui-kit'
import * as common from '@/utils/common'
</script>

<template ts-ignore>
  <MDBModal tag="form" id="addDataModal" tabindex="-1" v-model="common.showAddDataModal.value"
    @submit.prevent="common.submit()">
    <MDBModalHeader>
      <MDBModalTitle v-if="common.addDataModalRaiseType.value === 'add'"> 添加信息 </MDBModalTitle>
      <MDBModalTitle v-if="common.addDataModalRaiseType.value === 'edit'"> 修改信息 </MDBModalTitle>
    </MDBModalHeader>
    <MDBModalBody>

      <div v-for="column in common.columns.value">
        <div v-if="// @ts-ignore
        column.type === 'boolean'" class="ms-1">
          <span>{{ // @ts-ignore
          column.label }}</span>
          <div v-if="// @ts-ignore
          column.field === 'gender'" class="d-flex flex-row mb-3">
            <MDBRadio :disabled="// @ts-ignore
            column.autoGenerated === true" :is-valid="column.isValid" isValidated label="男"
              value="true" v-model="common.data.value[column.field]" inline />
            <MDBRadio :disabled="// @ts-ignore
            column.autoGenerated === true" :is-valid="column.isValid" isValidated label="女"
              value="false" v-model="common.data.value[column.field]" inline />
          </div>
          <div v-else class="d-flex flex-row mb-3">
            <MDBRadio :disabled="// @ts-ignore
            column.autoGenerated === true" :is-valid="column.isValid" isValidated label="是"
              value="true" v-model="common.data.value[column.field]" inline />
            <MDBRadio :disabled="// @ts-ignore
            column.autoGenerated === true" :is-valid="column.isValid" isValidated label="否"
              value="false" v-model="common.data.value[column.field]" inline />
          </div>
        </div>
        <MDBInput v-else required :disabled="// @ts-ignore
        column.autoGenerated === true"
          :label="column.label + (column.autoGenerated ? '（自动生成）' : '')" v-model="common.data.value[column.field]"
          class="mb-md-4" :type="column.type" @change="// @ts-ignore
          column.validator(common.data.value[column.field])"
          :is-valid="column.isValid" isValidated />
      </div>

    </MDBModalBody>
    <MDBModalFooter>
      <MDBBtn color="secondary" @click="common.onCloseModal()">关闭</MDBBtn>
      <MDBBtn color="primary" type="submit" :disabled="// @ts-ignore
      common.columns.value.findIndex(item => {
        return item.isValid === false
      }) !== -1">
        保存
    </MDBBtn>
  </MDBModalFooter>
</MDBModal></template>